# Target specific macros
TARGET = maxmotorrotationtest
TARGET_SOURCES := \
maxmotorrotationtest.c
TOPPERS_OSEK_OIL_SOURCE := ./maxmotorrotationtest.oil

O_PATH ?= build

include ../ecrobot/ecrobot.mak

