/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "speedometer.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void testConvertRawDataToTicks0();
extern void testConvertRawDataToTicks1();
extern void testConvertRawDataToTicks2();
extern void testConvertRawDataToTicks3();
extern void testConvertRawDataToTicksBadData();
extern void testUpdateSpeedometerDataForward();
extern void testUpdateSpeedometerDataBackward();
extern void testUpdateSpeedometerDataStopped();
extern void testAddToArrayFront();
extern void testAddToArrayBack();
extern void testCalculateVelocity();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "speedometerTest/speedometerTest.c";
  printf("\n------TEST RESULTS-----\n");
  printf("speedometerTest/speedometerTest.c\n");
  printf("-----------------------\n");
  UnityBegin();
  RUN_TEST(testConvertRawDataToTicks0, 14);
  RUN_TEST(testConvertRawDataToTicks1, 22);
  RUN_TEST(testConvertRawDataToTicks2, 30);
  RUN_TEST(testConvertRawDataToTicks3, 38);
  RUN_TEST(testConvertRawDataToTicksBadData, 46);
  RUN_TEST(testUpdateSpeedometerDataForward, 54);
  RUN_TEST(testUpdateSpeedometerDataBackward, 74);
  RUN_TEST(testUpdateSpeedometerDataStopped, 94);
  RUN_TEST(testAddToArrayFront, 114);
  RUN_TEST(testAddToArrayBack, 124);
  RUN_TEST(testCalculateVelocity, 134);

  UnityEnd();
  return (0);
}
