/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "abs.h"
#include "speedometer.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void testEngineIsStopped();
extern void testBrakeRateLessPower();
extern void testBrakeRateMorePower();
extern void testBrakeRateDivBy0();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "absTest/absTest.c";
  printf("\n------TEST RESULTS-----\n");
  printf("absTest/absTest.c\n");
  printf("-----------------------\n");
  UnityBegin();
  RUN_TEST(testEngineIsStopped, 24);
  RUN_TEST(testBrakeRateLessPower, 38);
  RUN_TEST(testBrakeRateMorePower, 53);
  RUN_TEST(testBrakeRateDivBy0, 68);

  UnityEnd();
  return (0);
}
