/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "laneControl.h"
#include "eaeb.h"
#include "controller.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void testDetectRoadMarkingRight();
extern void testDetectRoadMarkingLeft();
extern void testDetectNoRoadMarking();
extern void testCalibrateRoadMarkingReadings();
extern void testEmptyArray();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "laneControlTest/laneControlTest.c";
  printf("\n------TEST RESULTS-----\n");
  printf("laneControlTest/laneControlTest.c\n");
  printf("-----------------------\n");
  UnityBegin();
  RUN_TEST(testDetectRoadMarkingRight, 26);
  RUN_TEST(testDetectRoadMarkingLeft, 44);
  RUN_TEST(testDetectNoRoadMarking, 62);
  RUN_TEST(testCalibrateRoadMarkingReadings, 81);
  RUN_TEST(testEmptyArray, 105);

  UnityEnd();
  return (0);
}
