# Target specific macros
TARGET = mainSW502E13

TARGET_SOURCES := \
main.c \
nxt_interface.c \
abs.c \
datalog.c \
controller.c \
aeb.c \
eaeb.c \
speedometer.c

TOPPERS_OSEK_OIL_SOURCE := ./main.oil

O_PATH ?= build

include ../../ecrobot/ecrobot.mak

