# Target specific macros
TARGET = SpeedometerTest

TARGET_SOURCES := \
nxt_interface.c \
speedometer.c \
SpeedometerTest.c

TOPPERS_OSEK_OIL_SOURCE := ./SpeedometerTest.oil

O_PATH ?= build

include ../ecrobot/ecrobot.mak

