/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "controller.h"
#include "stdio.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void testReceiveBT();
extern void testControlSteering();
extern void testControlSteeringTurnDeg();
extern void testControlSteeringsLash();
extern void testControlMotorsGoodParams();
extern void testControlMotorsHighSpeed();
extern void testControlMotorsLowSpeed();
extern void testTurnDegreesUnder();
extern void testTurnDegreesOver();
extern void testTurnDegreesOn();
extern void testTurnDegreesAlreadyTurnedPos();
extern void testTurnDegreesAlreadyTurnedNeg();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "controllerTest/controllerTest.c";
  printf("\n------TEST RESULTS-----\n");
  printf("controllerTest/controllerTest.c\n");
  printf("-----------------------\n");
  UnityBegin();
  RUN_TEST(testReceiveBT, 16);
  RUN_TEST(testControlSteering, 33);
  RUN_TEST(testControlSteeringTurnDeg, 46);
  RUN_TEST(testControlSteeringsLash, 60);
  RUN_TEST(testControlMotorsGoodParams, 71);
  RUN_TEST(testControlMotorsHighSpeed, 90);
  RUN_TEST(testControlMotorsLowSpeed, 109);
  RUN_TEST(testTurnDegreesUnder, 128);
  RUN_TEST(testTurnDegreesOver, 137);
  RUN_TEST(testTurnDegreesOn, 146);
  RUN_TEST(testTurnDegreesAlreadyTurnedPos, 155);
  RUN_TEST(testTurnDegreesAlreadyTurnedNeg, 167);

  UnityEnd();
  return (0);
}
