/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "tcs.h"
#include "speedometer.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void testLowerSpeedWhenSlipping();
extern void testLowerSpeedWhenBothReverse();
extern void testLowerSpeedWhenBackReverse();
extern void testLowerSpeedWhenFrontReverse();
extern void testRemainSpeedWhenNotSlipping();
extern void testRemainSpeedWhenNotSlippingBothReverse();
extern void testRemainSpeedWhenNotSlippingBackReverse();
extern void testRemainSpeedWhenNotSlippingFrontReverse();
extern void testRemainSpeedWhenBraking();
extern void testRemainSpeedWhenBrakingNegative();


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "tcsTest/tcsTest.c";
  printf("\n------TEST RESULTS-----\n");
  printf("tcsTest/tcsTest.c\n");
  printf("-----------------------\n");
  UnityBegin();
  RUN_TEST(testLowerSpeedWhenSlipping, 27);
  RUN_TEST(testLowerSpeedWhenBothReverse, 38);
  RUN_TEST(testLowerSpeedWhenBackReverse, 49);
  RUN_TEST(testLowerSpeedWhenFrontReverse, 60);
  RUN_TEST(testRemainSpeedWhenNotSlipping, 76);
  RUN_TEST(testRemainSpeedWhenNotSlippingBothReverse, 88);
  RUN_TEST(testRemainSpeedWhenNotSlippingBackReverse, 100);
  RUN_TEST(testRemainSpeedWhenNotSlippingFrontReverse, 112);
  RUN_TEST(testRemainSpeedWhenBraking, 124);
  RUN_TEST(testRemainSpeedWhenBrakingNegative, 136);

  UnityEnd();
  return (0);
}
